<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>registerActivationLink</name>
   <tag></tag>
   <elementGuidId>653a485b-0c80-4718-95e6-7cb035b2b36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mail&quot;]/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[2]/td/p[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
